name: dotnet-runtime-60
base: core18
version: 6.0.26
summary: Cross-Platform .NET Core Runtime. 
description: |
  .NET Core runtimes and libraries which are optimized for running .NET Core apps in production. See https://dot.net/core.
  .NET Core is a general purpose development platform maintained by Microsoft. 

grade: stable
confinement: strict

apps:
  dotnet:
    command: dotnet
    plugs:
      - network
      - network-bind
      - removable-media
      - home

slots:
  dotnet-runtime:
    content: dotnet-runtime-60
    interface: content
    read: [/]

parts:
  dotnet-runtime:
    plugin: dump
    source: https://download.visualstudio.microsoft.com/download/pr/1873e7f3-aa12-4189-8d6d-db0fb859211e/b36e8f8a6ceb63bc3cfac875c7bb63d0/dotnet-runtime-6.0.26-linux-x64.tar.gz
    source-checksum: sha512/7336f71f7f99ffc3a44c7d730c6a1e08c5c0b6e05d2076a1963776f174f8588d31c9b783d1c4f645f7e7cc6a54077b798c6bde35ed4a812ffd9b2427d29b0b34
    stage-packages:
      - libicu60
      - libssl1.0.0
      - libcurl3
      - libgssapi-krb5-2
      - liblttng-ust0
      - libstdc++6
      - zlib1g
      - libgcc1
      - libtinfo5
      - libdb5.3
      - libc6
