name: dotnet-runtime-80
base: core18
version: 8.0.1
summary: Cross-Platform .NET Core Runtime. 
description: |
  .NET Core runtimes and libraries which are optimized for running .NET Core apps in production. See https://dot.net/core.
  .NET Core is a general purpose development platform maintained by Microsoft. 

grade: stable
confinement: strict

apps:
  dotnet:
    command: dotnet
    plugs:
      - network
      - network-bind
      - removable-media
      - home

slots:
  dotnet-runtime:
    content: dotnet-runtime-80
    interface: content
    read: [/]

parts:
  dotnet-runtime:
    plugin: dump
    source: https://download.visualstudio.microsoft.com/download/pr/4d5166de-c1ac-45c5-bb8a-d47f8ee93ad9/ffab59440a3eb74359dd3009e4da5a81/dotnet-runtime-8.0.1-linux-x64.tar.gz
    source-checksum: sha512/cbd03325280ff93cd0edab71c5564a50bb2423980f63d04602914db917c9c811a0068d848cab07d82e3260bff6684ad7cffacc2f449c06fc0b0aa8f845c399b6
    stage-packages:
      - libicu60
      - libssl1.0.0
      - libcurl3
      - libgssapi-krb5-2
      - liblttng-ust0
      - libstdc++6
      - zlib1g
      - libgcc1
      - libtinfo5
      - libdb5.3
      - libc6

