name: dotnet-runtime-80
base: core18
version: 8.0.0-preview.5.23280.8
summary: Cross-Platform .NET Core Runtime. 
description: |
  .NET Core runtimes and libraries which are optimized for running .NET Core apps in production. See https://dot.net/core.
  .NET Core is a general purpose development platform maintained by Microsoft. 

architectures:
  - build-on: amd64
    run-on: amd64

grade: stable
confinement: strict
base: core20

slots:
  dotnet-runtime:
    content: dotnet-runtime-60
    interface: content
    read: [/]

parts:
  dotnet-runtime:
    plugin: dump
    source: https://download.visualstudio.microsoft.com/download/pr/bbdc7ec0-d87e-4b6b-bb3f-9dbe5db3078e/6cda9733bbedf8f4fb9e18829e301051/dotnet-runtime-8.0.0-preview.5.23280.8-linux-x64.tar.gz
    source-checksum: sha512/0fa3d9bef5300533b4f266fc1983c7bc8eb55c6c9e8ddf86978a3adb911663a2069c9ed9e428f8d2361558a40edef5bfad6ef75ea2a728cf700a23cd38e7bbcc
    stage-packages:
      - libicu66
      - libssl1.1
      - libcurl4
      - libgssapi-krb5-2
      - liblttng-ust0
      - libstdc++6
      - zlib1g
      - libgcc1
      - libtinfo5
      - libdb5.3
      - libc6

apps:
  dotnet:
    command: dotnet
    plugs:
      - network
      - network-bind
      - removable-media
      - home